name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build Docusaurus
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: "21"

            - name: Cache Node Modules
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install dependencies
              run: npm ci

            - name: Cache Docusaurus Build
              uses: actions/cache@v4
              with:
                  path: .docusaurus
                  key: ${{ runner.os }}-docusaurus-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', '**/*.md') }}
                  restore-keys: |
                      ${{ runner.os }}-docusaurus-

            - name: Build website
              run: npm run build

            - name: Upload Build Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: build

    deploy:
        name: Deploy to GitHub Pages
        needs: build

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
